### ISSUE TITLE
401 error: 

### ISSUE THREAD

**Issue by Rishikeshpal** [Hygieia/hygieia-perf-appdynamics-collector#2]
2019-09-25 13:41:28,903 [main] INFO  com.capitalone.dashboard.Application - Started Application in 10.443 seconds (JVM running for 11.664)
2019-09-25 13:42:01,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Appdynamics
2019-09-25 13:42:01,028 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-09-25 13:42:01,028 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Instance 0: https://gw-test.saas.appdynamics.com/
2019-09-25 13:42:01,028 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2019-09-25 13:42:01,805 [taskScheduler-1] ERROR c.c.d.c.DefaultAppdynamicsClient - client exception loading applications
org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultAppdynamicsClient.makeRestCall(DefaultAppdynamicsClient.java:418) ~[appdynamics-performance-collector-3.1.0-SNAPSHOT.jar!/:3.1.0-SNAPSHOT]

my api.properties file.
dbname=dashboarddb
dbhost=localhost
dbport=27017
dbreplicaset=false
dbhostport=localhost:27017
logging.file=./logs/appd-collector.log
appdynamics.cron=1 * * * * *
appdynamics.instanceUrls=https://gw-test.saas.appdynamics.com/
appdynamics.username=hygieia
appdynamics.password=xxxxx@1234
appdynamics.dashboardUrls=https://xx-test.saas.appdynamics.com/controller/#/location=CDASHBOARD_DETAIL&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&mode=MODE_DASHBOARD&dashboard=3536

i created a local user called hygieia and password is xxxxx@1234

**Comment by Rishikeshpal** [comment]
closing this as i fixed by specifying the account with my login in api.propertiesfile.

**Comment by Rishikeshpal** [comment]
closing this as i fixed by specifying the account with my login in api.propertiesfile.

**Comment by kapil5kc** [comment]
Hi @Rishikeshpal can you share the api.properties please? how to add account with login details?
I am stuck at same issue.
